on: push
name: 🚀 Build Sass and deploy website on push
jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run parcel build ./src/index.html

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ssh.strato.com
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          port: 22
          uploads: ./dist/ => ./the-victory-template/
