on: push
name: 🚀 Build Sass and deploy website on push
# jobs:
#   build_css:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source Git branch
#         uses: actions/checkout@v2
#         with:
#             ref: src-pages
#             fetch-depth: 10
#             submodules: true

#       - name: Make destination directory for compiled CSS
#         run: mkdir -vp /tmp/repo-name/assets/css

#       - name: Compile CSS from SCSS files
#         uses: gha-utilities/sass-build@v0.6.0
#         with:
#           source: src/scss/main.scss
#           destination: /tmp/repo-name/assets/css/main.css

#       - name: Checkout destination Git branch
#         uses: actions/checkout@v2
#         with:
#             ref: pr-pages
#             fetch-depth: 1

#       - name: Move compiled CSS to path within pr-pages branch
#         run: mv /tmp/repo-name/assets/css assets/

#       - name: Add and Commit changes to pr-pages branch
#         run: |
#           git config --local user.email 'action@github.com'
#           git config --local user.name 'GitHub Action'
#           git add assets/css/*
#           git commit -m 'Updates compiled CSS files'

#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: pr-pages

#       - name: Initialize Pull Request
#         uses: gha-utilities/init-pull-request@v0.0.4
#         with:
#           pull_request_token: ${{ secrets.GITHUB_TOKEN }}
#           head: pr-pages
#           base: gh-pages
#           title: 'Updates site files from latest Actions build'
#           body: >
#             Perhaps a multi-line description
#             about latest features and such.

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ssh.strato.com
          username: 511198519.swh.strato-hosting.eu
          password: ${{ secrets.ftp_password }}
          local-dir: ./src/
          server-dir: /wp-content/themes/the-victory-template
