on: push
name: 🚀 Build Sass and deploy website on push
jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: sftp.server.com
          username: jason-bourne
          password: ${{secrets.FTP_PASSWORD}}
          port: 22
          uploads: ./src/ => ./wp-content/themes/the-victory-template/
